name: Build and deploy
on:
  push:
    branches: [ pages ]
jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Inject GA
      run: git -C themes/hyde/ apply ../../patches/0001-Add-Google-Analytics.patch
    - name: Deploy Zola
      uses: shalzz/zola-deploy-action@master
      env:
        PAGES_BRANCH: master
        BUILD_FLAGS: --drafts
        TOKEN: ${{ secrets.deploy_token }}
